# Set the version of docker compose to use
version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - shadow
    environment:
      WAIT_HOSTS: database:5432, shadow:5432
    ports:
      - 4000:4000
    volumes:
      - ./:/app

  database:
    image: postgres:14.2
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      DATABASE_URL: postgresql://prisma:prisma@database:5432/reformat
    volumes:
      - app-pg-database:/var/lib/postgresql/data/
  
  shadow:
    image: postgres:14.2
    environment:
      POSTGRES_USER: prismaShadow
      POSTGRES_PASSWORD: prismaShadow
      DATABASE_URL: postgresql://prismaShadow:prismaShadow@shadow:5432/reformatShadow
    ports:
      - 5433:5432
    volumes:
      - app-pg-shadow:/var/lib/postgresql/data/


volumes:
  app-pg-database:
  app-pg-shadow:
